#!/system/bin/sh
# An unforunate wrapper script
# so that the exit code of pppd may be retrieved


# this is a workaround for issue #651747
#trap "/system/bin/sleep 1;exit 0" TERM


PPPD_PID=
MODEM_USB=`/system/bin/getprop hw.radio.modemport`

/system/bin/setprop "net.gprs.ppp-exit" ""
/system/bin/setprop "net.gprs.ppping" "dialing"

/system/bin/log -t pppd "Starting pppd"
/system/bin/log -t pppd "use modem port $MODEM_USB"

#/system/bin/pppd $*
/system/bin/pppd connect 'chat -vVs "" "AT" "OK" "ATDT*99#"' $MODEM_USB 115200 nodetach crtscts debug usepeerdns defaultroute


PPPD_EXIT=$?
PPPD_PID=$!

/system/bin/log -t pppd "pppd exited with $PPPD_EXIT"

/system/bin/setprop "net.gprs.ppp-exit" "$PPPD_EXIT"
/system/bin/setprop "net.gprs.ppping" ""

#echo AT+CREG? > /dev/ttyUSB2
/system/bin/radiooptions 14
