#!/system/bin/sh
# An unforunate wrapper script 
# so that the exit code of pppd may be retrieved


#PPPD_PID=""
PPPD_EXIT=""

/system/bin/setprop "net.gprs.ppp-exit" ""

/system/bin/log -t pppd "Starting pppd"

/system/bin/pppd ttyACM0 115200 nodetach noauth noipdefault defaultroute usepeerdns connect "chat -v '' AT OK ATD*99# CONNECT" debug

PPPD_EXIT=$?
#PPPD_PID=$!

#/system/bin/log -t pppd "pppd pid: $PPPD_PID"
/system/bin/log -t pppd "pppd exited with $PPPD_EXIT"

/system/bin/setprop "net.gprs.ppp-exit" "$PPPD_EXIT"
